version: '3'
services:
  app:
    container_name: ${APP_CONTAINER_NAME}
    restart: always
    build: .
    ports:
      - '${APP_PORT}:${APP_PORT}'
      # - '${EMAIL_PORT}:${EMAIL_PORT}'
    environment:
      APP_PORT: ${APP_PORT}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}   
      APP_DOMAIN: ${APP_DOMAIN}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_RECIVER: ${EMAIL_RECIVER}
    links:
      - mysql
  mysql:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'    
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    ports:
      - '${MYSQL_PORT}:3306'
    expose:
      - '${MYSQL_PORT}'